rtabmap:
  ros__parameters:
    use_sim_time: true
    delete_db_on_start: true
    approx_sync: true
    sync_queue_size: 30
    topic_queue_size: 30
    approx_sync_max_interval: 0.1  # Accept up to 100ms difference
    qos_image: 1
    qos_odom: 1
    frame_id: "base_footprint"
    subscribe_depth: false
    subscribe_rgbd: true
    subscribe_scan: false
    subscribe_scan_cloud: false
    subscribe_stereo: false
    subscribe_user_data: false
    

    # ✅ Enable 3D mapping and color
    RGBD/CreateRGB: "true"
    CloudRGB: "true"
    Grid/3D: "true"
    RGBD/CreateRGB: "true"
    CloudRGB: "true"

    # Optional tuning
    Vis/MinInliers: "10"
    Mem/STMSize: "30"
    Reg/Strategy: "0"  # visual-only

rgbd_sync:
  ros__parameters:
    approx_sync: true
    sync_queue_size: 30
    topic_queue_size: 30
    approx_sync_max_interval: 0.1  # Accept up to 100ms difference
    frame_id: "base_footprint"
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: false
    subscribe_scan_cloud: false
    subscribe_stereo: false
    subscribe_user_data: false
    odom_sensor_sync: true
    

rtabmap_viz:
  ros__parameters:
    approx_sync: true
    sync_queue_size: 30
    topic_queue_size: 30
    approx_sync_max_interval: 0.1  # Accept up to 100ms difference
    frame_id: "base_footprint"
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: false
    subscribe_scan_cloud: false
    subscribe_stereo: false
    subscribe_user_data: false


    # ✅ Enable 3D mapping and color visualization
    RGBD/CreateRGB: "true"
    CloudRGB: "true"
    Grid/3D: "true"
    RGBD/CreateRGB: "true"
    CloudRGB: "true"

    # Optional tuning for visualization
    Vis/MinInliers: "10"
    Mem/STMSize: "30"