ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    sensor_timeout: 0.1

    two_d_mode: true

    # Set only IMU enabled
    imu0: /imu_plugin/out
    imu0_config: [false, false, false,  # x, y, z position
                  true,  true,  true,   # roll, pitch, yaw
                  true,  true,  false,  # x, y, z velocity
                  false, false, false]  # roll, pitch, yaw velocity

    imu0_differential: false
    imu0_relative: true

    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom


    odom0: /osr/odom
    odom0_config: [true, true, false,
                  false, false, true,
                  true, true, false,
                  false, false, false]
    odom0_differential: false
    odom0_relative: true